[package]
name = "rpc-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-channel = "0.3"
tokio = { version = "1.0.0", default-features = false, features = ["io-util", "io-std", "macros", "net", "rt-multi-thread", "time", "sync"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
async-trait = "0.1.57"
async-channel = "1.8.0"
tokio-util = "0.7.4"
tokio-tungstenite = "*"
log = "0.4.17"
bytes = "1.3.0"
prost = "0.11.5"
quinn = "*"
rustls = { version = "*", features = ["dangerous_configuration", "quic"] }

[build-dependencies]
prost-build = "0.11.5"

[dev-dependencies]
prost-build = "0.11.5"
