name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Protobuf
        run: sudo apt-get install protobuf-compiler
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${CRATES_TOKEN} -p dcl-rpc
        env:
          CRATES_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
      - run: cargo publish --token ${CRATES_TOKEN} -p dcl-rpc-codegen
        env:
          CRATES_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
