name: Validations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
